#          ╭──────────────────────────────────────────────────────────╮
#          │ config                                                   │
#          ╰──────────────────────────────────────────────────────────╯
logging-to-file = true         # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

#  ╭──────────╮
#  │ Revanced │       = RVX
#  ╰──────────╯
# [Revanced] # Normal Revanced
# rv-brand = "O-Vanced"
# exclusive-patches = true # exclude all patches by default. default: false
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# uptodown-arch = "arm64-v8a"
# version = "auto"                                        # latest, auto
# included-patches = "remove-player-controls-background "
# excluded-patches = "tablet-mini-player theme "


#  ╭─────────────────────────╮
#  │ Revanced Extenends here │       RVX
#  ╰─────────────────────────╯

[RvX] # RVX = Revanced Extended
rv-brand = "Extended"
app-name = "-YomaruExt"
exclusive-patches = true # exclude all patches by default. default: false
version = "auto"                                        # latest, auto
build-mode = "apk"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
# included-patches = "add-splash-animation disable-landscape-mode custom-branding-icon-mmt force-hide-player-button-background force-premium-heading hide-double-tap-overlay-filter materialyou"
# excluded-patches = "custom-branding-icon-revancify-blue custom-package-name disable-quic-protocol enable-tablet-mini-player force-opus-codec force-vp9-codec translations"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-arch = "arm64-v8a"
#
# [MusicRex]
# # rv-brand = "Extended-Muxik"
# # app-name = "MoMaru"
# module-prop-name = "ytm-rvx"
# patches-source = "inotia00/revanced-patches"
# integrations-source = "inotia00/revanced-integrations"
# cli-source = "inotia00/revanced-cli"
# build-mode = "apk"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
# apkmirror-arch = "arm64-v8a"
#
#
# #  ╭───────────────────╮
# #  │ ReVanced Advanced │
# #  ╰───────────────────╯
#
 [ReX] # ReX = Revanced Advanced
rv-brand = "YO-ADvanced"
 app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "YT-Advanced/revanced-cli"              # use this one till YT-Advanced updates it
# cli-source = "j-hc/revanced-cli"  # only supprot Rvx
 # apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-arch = "arm64-v8a"
version = "18.32.39"
included-patches = "higher-seekbar-height amoled custom-branding-icon-mmt hide-end-screen-overlay hide-navigation-buttons hide-player-button-background hide-navigation-label hide-end-screen-overlay enable-new-thumbnail-preview  enable-new-splash-animation force-hide-player-button-background force-premium-heading hide-double-tap-overlay-filter language-switch optimize-resource translations materialyou"
excluded-patches = "custom-branding-icon-revancify-blue disable-quic-protocol enable-tablet-mini-player force-opus-codec force-vp9-codec "
#
#
# [Music-X] # Music - Advanced  YT-Advanced
# rv-brand = "O-Music-Advanced"
# app-name = "OxMusic"
# enabled = true
# # apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-arch = "arm64-v8a"
# uptodown-arch = "arm64-v8a"
# patches-source = "YT-Advanced/ReX-patches"
# integrations-source = "YT-Advanced/ReX-integrations"
# cli-source = "YT-Advanced/revanced-cli"
# excluded-patches = " "
# included-patches = " "
#
#
# #  ╭──────────────╮
# #  │ Experemental │
# #  ╰──────────────╯
# # [Spotify] # for testing purpose only
# # enabled = true
# # uptodown-dlurl = "https://spotify.en.uptodown.com/android"
