logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

### OLD STUFF            | Rvx = Revanced Extended
# [RvX]
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# patches-source = "inotia00/revanced-patches"
# integrations-source = "inotia00/revanced-integrations"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "O-Extended"
# included-patches = "add-splash-animation disable-landscape-mode custom-branding-icon-mmt force-hide-player-button-background force-premium-heading hide-double-tap-overlay-filter materialyou"
# excluded-patches = "custom-branding-icon-revancify-blue custom-package-name disable-quic-protocol enable-tablet-mini-player force-opus-codec force-vp9-codec translations"



# [Revanced]
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# version = "latest"
# included-patches = "remove-player-controls-background"
# excluded-patches = "tablet-mini-player theme"
#
#
[ReX]
rv-brand = "O-Advanced"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli" # use this one till YT-Advanced updates it
# cli-source = "j-hc/revanced-cli"  # only supprot Rvx
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "amoled hide-end-screen-overlay hide-navigation-buttons hide-player-button-background hide-navigation-label hide-end-screen-overlay enable-new-thumbnail-preview custom-branding-icon-mmt enable-new-splash-animation force-hide-player-button-background force-premium-heading hide-double-tap-overlay-filter language-switch optimize-resource materialyou"
excluded-patches = "custom-branding-icon-revancify-blue disable-quic-protocol enable-tablet-mini-player force-opus-codec force-vp9-codec translations"
  
    

# [Music-Extended]
# app-name = "Music"
# patches-source = "YT-Advanced/ReX-patches"
# integrations-source = "YT-Advanced/ReX-integrations"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "ReVanced Extended"
# build-mode = "both"
# excluded-patches = "custom-branding-icon-revancify-blue"
# included-patches = "custom-branding-icon-mmt"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
# apkmirror-arch = "both"
#
