enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "both"                                                     # "arm64-v8a"
build-mode = "apk"
version = "auto"
included-patches = "'Enable slide to seek' 'Custom branding' 'Remove player controls background'"
excluded-patches = ""
patcher-args = "-OappName=YoMaru -OiconPath=icons "


# │ Revanced Extenends here │       RVX
[RvX] #
app-name = "RvX"
rv-brand = "Ext"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
integrations-source = "inotia00/revanced-integrations"
build-mode = "apk"                                                # apk = "apk" or magisk zip = "module"
arch = "both"                                                     # "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Enable slide to seek' 'Custom branding' 'Remove player controls background'"
excluded-patches = ""
patcher-args = "-OappName=YoMaruExt -OiconPath=icons "
# excluded-patches = ""
# included-patches = ""

[Music]
build-mode = "apk"                                                # apk = "apk" or magisk zip = "module"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
included-patches = "'Permanent repeat' 'Hide category bar'"

[Muisc-RvX]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "both"
build-mode = "apk"                                                # apk = "apk" or magisk zip = "module"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
integrations-source = "inotia00/revanced-integrations"
included-patches = "'Custom header for YouTube Music' 'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter' 'Return YouTube Username'"
# patcher-args = "-OappIcon=MusicIcon -OappNameLauncher=MusicExt "

[Reddit_old]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "both"

[Reddit]
patches-source = "inotia00/revanced-patches"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
# cli-source = "inotia00/revanced-cli"
integrations-source = "inotia00/revanced-integrations"
arch = "both"
apkmirror-dpi = "120-640dpi"                               # used to select apk variant from apkmirror. default: nodpi
patcher-args = "-e 'Change package name' -OpackageNameReddit=com.yomaru.red -e 'Custom branding name for Reddit' -OappName='Redd Manager' "


[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
arch = "both"
# included-patches = "'Spoof signature' 'Unlock Spotify Premium' 'Custom theme' 'Predictive back gesture' 'Remove screen capture restriction' 'Remove screenshot restriction' 'Export all activities' 'Spoof SIM country' 'Hide mock location' 'Spoof Wi-Fi connection' 'Export internal data documents provider'"
