logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true
#patches-documentation       https://github.com/ReVanced-Extended-Community/Patches-Documentation

#  ╭──────────╮
#  │ Revanced │       
#  ╰──────────╯
# [Revanced] # Normal Revanced
# # rv-brand = "O-Vanced"
# # exclusive-patches = true                                          # exclude all patches by default. default: false
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# uptodown-arch = "arm64-v8a"
# version = "18.32.39"                                              # latest, auto
# # included-patches = "remove-player-controls-background "
# excluded-patches = "tablet-mini-player theme "

# #  ╭───────────────────╮
# #  │ ReVanced Advanced │                # now DEAD
# #  ╰───────────────────╯
#
# [ReX] # ReX = Revanced Advanced
# rv-brand = "YT-ADvanced"
# # app-name = "YouTube" 1st noneeded
# patches-source = "YT-Advanced/ReX-patches"
# integrations-source = "YT-Advanced/ReX-integrations"
# cli-source = "YT-Advanced/revanced-cli"              # use this one till YT-Advanced updates it
# # cli-source = "j-hc/revanced-cli"  # only supprot Rvx
# # apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# # uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# # apkmirror-arch = "arm64-v8a"   # its giving error on most
# version = "18.32.39"
# # build-mode = "both"
# included-patches = "higher-seekbar-height amoled custom-branding-icon-mmt hide-end-screen-overlay hide-navigation-buttons hide-player-button-background hide-navigation-label hide-end-screen-overlay enable-new-thumbnail-preview  enable-new-splash-animation force-hide-player-button-background force-premium-heading hide-double-tap-overlay-filter language-switch  translations materialyou"
# excluded-patches = "custom-branding-icon-revancify-blue disable-quic-protocol enable-tablet-mini-player force-opus-codec force-vp9-codec "
#
# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "apk"
# excluded-patches = ""
# included-patches = ""
# version = "auto"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


#  ╭─────────────────────────╮
#  │ Revanced Extenends here │       RVX
#  ╰─────────────────────────╯

[RvX] # RVX = Revanced Extended
app-name = "Yomaru" # commes first in file naming
rv-brand = "Ext"    # comes secodn in file naming
# exclusive-patches = true                               # exclude all patches by default. default: false
version = "18.37.36" # latest or auto
# build-mode = "both"          # apk = "apk" or magisk zip = "module"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"                   # having issue using j-hc cli source now
# included-patches = " 'Custom branding icon MMT' "
# excluded-patches = " 'Custom branding icon Revancify blue' 'Custom branding icon Revancify red' "


included-patches = " 'Enable gradient loading screen' 'Enable language switch' 'Add splash animation' 'Custom speed overlay' 'Alternative thumbnails' 'Bypass ambient mode restrictions' 'Custom branding icon MMT' 'Custom branding youtube name' 'Custom double tap length' 'Custom package name' 'Default video quality' 'Custom playback speed' 'Disable haptic feedback' 'Disable hdr video' 'Disable pip notification' 'Disable quic protocol' 'Disable shorts on startup' 'Enable compact controls overlay' 'Enable external browser' 'Enable minimized playback' 'Enable new comment popup panels' 'Enable new splash animation' 'Enable new thumbnail preview' 'Enable old quality layout' 'Enable open links directly' 'Enable seekbar tapping' 'Append time stamps information' 'Enable wide search bar' 'Force hide player button background' 'Force premium heading' 'Header switch' 'Force opus codec' 'Force video codec' 'Enable HDR codec' 'Hide account menu' 'Hide auto player popup panels' 'Hide autoplay button' 'Hide button container' 'Hide category bar' 'Hide cast button' 'Hide channel watermark' 'Hide collapse button' 'Hide comment component' 'Hide crowdfunding box' 'Hide description components' 'Hide double tap overlay filter' 'Hide handle' 'Hide endscreen cards' 'Hide endscreen overlay' 'Hide feed flyout panel' 'Hide filmstrip overlay' 'Hide floating microphone' 'Hide fullscreen panels' 'Hide general ads' 'Hide video ads' 'Hide info cards' 'Hide latest videos button' 'Hide layout components' 'Hide mix playlists' 'Hide music button' 'Hide navigation buttons' 'Hide navigation label' 'Hide player button background' 'Hide player flyout panel' 'Hide player overlay filter' 'Hide previous next button' 'Hide quick actions' 'Hide seek message' 'Hide shorts components' 'Hide snack bar' 'Hide suggested actions' 'Hide suggested video overlay' 'Hide suggestions shelf' 'Hide time stamp' 'Hide tooltip content' 'Hide trending searches' 'Language switch' 'Layout switch' 'Microg support' 'MaterialYou' 'Overlay buttons' 'Return youtube dislike' 'Settings' 'Sponsorblock' 'Hook download button' 'Spoof app version' 'Spoof player Parameters' 'Swipe Controls' 'Hide channel profile links' 'Theme' "
# # add-splash-animation dosen't work with custom-branding-icon

excluded-patches = " 'Custom branding icon Revancify Blue' 'Custom branding icon Revancify Red' 'Custom seekbar color' 'Disable auto captions' 'Disable landscape mode' 'Enable debug logging' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Hide autoplay preview' 'Hide captions button' 'Hide channel avatar section' 'Hide load more button' 'Hide seekbar' 'Translations' "
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"


# [MusicRex]
# rv-brand = "YTM"
# # app-name = "MoMaru"
# module-prop-name = "ytm-rvx"
# patches-source = "inotia00/revanced-patches"
# integrations-source = "inotia00/revanced-integrations"
# cli-source = "inotia00/revanced-cli"
# build-mode = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-arch = "arm64-v8a"
